---
title: "Maroubra"
format: html
editor: visual
---

## Maroubra data

```{r}

library(tidyverse)
library(easystats)
library(patchwork)

gastropods <- read_csv("data/MaroubraZones_2024.csv") %>%
  rename(Zone = elevation)
```

```{r}

# make elevation (zone) a factor that is ordered
gastropods <- 
  gastropods %>% 
  mutate(Zone = factor(Zone, levels = c("Low", "Mid", "High")))

# subset data
Austrocochlea <- gastropods %>% filter(species == "Austrocochlea") 
 
Cellana <-  gastropods %>% filter(species == "Cellana") 

Nerita <-  gastropods %>% filter(species == "Nerita")

# plot

ggplot(Austrocochlea, aes(Zone, abundance)) + 
  geom_boxplot()

ggplot(Cellana, aes(Zone, abundance)) + 
  geom_boxplot()

ggplot(Nerita, aes(Zone, abundance)) + 
  geom_boxplot()

Nerita_summary <- Nerita %>% 
   group_by(Zone) %>% 
   summarise(
     mean_Abundance = mean(abundance),
     sd_Abundance = sd(abundance),
     SE_Abundance = sd(abundance) / sqrt(n())
   )

ggplot(Nerita_summary , aes(Zone, mean_Abundance)) +
   geom_col() +
   geom_errorbar(aes(ymin = mean_Abundance - SE_Abundance, ymax = mean_Abundance + SE_Abundance), width=0.2)
```

```{r}

gastropods %>% 
  ggplot(aes(Zone, abundance)) + 
    geom_boxplot() +
    facet_wrap(~species)

```

```{r}

gastropods %>% 
  ggplot(aes(sheet, abundance)) + 
    geom_point() +
    facet_wrap(~species)
```

```{r}

Nerita.fit <- lm(abundance ~ Zone, data = Nerita) 
anova(Nerita.fit)
check_model(Nerita.fit)
performance(Nerita.fit)
```

```{r}

Nerita <- Nerita %>%
  mutate(abudance_sqrt = sqrt(abundance+1))

Nerita.fit.sqrt <- lm(abudance_sqrt ~ Zone, data = Nerita) 
anova(Nerita.fit.sqrt)
check_model(Nerita.fit.sqrt)
estimate_contrasts(Nerita.fit.sqrt) 
```

```{r}

Cellana.fit <- lm(abundance ~ Zone, data = Cellana) 
anova(Cellana.fit)
check_model(Cellana.fit)

```

```{r}

Cellana <- Cellana %>%
  mutate(abudance_sqrt = sqrt(abundance+1))

Cellana.fit.sqrt <- lm(abudance_sqrt ~ Zone, data = Cellana) 
anova(Cellana.fit.sqrt)
check_model(Cellana.fit.sqrt)
estimate_contrasts(Cellana.fit.sqrt) 
```

```{r}

Austrocochlea.fit <- lm(abundance ~ Zone, data = Austrocochlea) 
anova(Austrocochlea.fit)
check_model(Austrocochlea.fit)
```

```{r}

Austrocochlea <- Austrocochlea %>%
  mutate(abudance_sqrt = sqrt(abundance+1))

Austrocochlea.fit.sqrt <- lm(abudance_sqrt ~ Zone, data = Austrocochlea) 
anova(Austrocochlea.fit.sqrt)
check_model(Austrocochlea.fit.sqrt)
estimate_contrasts(Austrocochlea.fit.sqrt) 
```

```{r}

library(car)

Gastropods.ANOVA = lm(abundance ~ Zone * species, data = gastropods)

Anova(Gastropods.ANOVA, type = c("II"))
```

```{r}

 ggplot(gastropods, aes(species, abundance, fill=Zone)) + 
  geom_boxplot() 
```

```{r}

 Gastropods_summary <- 
  gastropods %>%
  group_by(species, Zone) %>%
  summarise(
     mean_Abundance = mean(abundance),
     sd_Abundance = sd(abundance),
    SE_Abundance = sd(abundance)/sqrt(n())
)
```

```{r}

Gastropods.fit <- lm(abundance ~ Zone * species, data = gastropods)

Gastropods.fit.complete <- lm(abundance ~ Zone + species + Zone:species, data = gastropods)


fitted <- estimate_means(Gastropods.fit)

plot(fitted)
```

```{r}

Gastropods_summary %>%
  ggplot(aes(Zone, mean_Abundance, fill = Zone)) +
  geom_col()  +
  facet_wrap(~species) +
  geom_errorbar(aes(ymin = mean_Abundance - SE_Abundance, ymax = mean_Abundance + SE_Abundance), width = 0.2)
```

ggplot(gastropods, aes(species, abundance, fill=Zone)) + geom_boxplot()
